### ISSUE TITLE
Beta testing code requested

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/spacedeck_ynh#3]
### Describe the bug

The app requires a beta code to create an account

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: 2021.08.10~ynh1

### Steps to reproduce

- Installed the app
- went to the web interface of the app to create an account

### Expected behavior

*The beta testing code should not required for the self-hosted version*

**Comment by yalh76** [comment]
Beta Invite Code can be retrieve executing from the command line `yunohost app setting spacedeck invite_secret`
