### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by 4abhinavjain** [YunoHost-Apps/spacedeck_ynh#6]
The speckdeck doesn't install on arm64 systems. Is there any plans to make an arm64 package?

**Comment by tituspijean** [comment]
> The speckdeck 

*Space*deck. 😉 
Do you mind sharing the log of your installation attempt? There does not seem to be actual limitation on the system architecture for the upstream app.

**Comment by 4abhinavjain** [comment]
Ah, my bad for the typo. Sure, this is the log. https://paste.yunohost.org/raw/arugosoxic

Seems like there is no arm64 candidate in https://github.com/sass/node-sass/releases/tag/v4.14.1

**Comment by tituspijean** [comment]
Thanks for the log! Indeed, no builds are available for ARM/ARM64 in node-sass. Additionally, two subsequent dependencies cannot be installed either, execSync and puppeteer. I'm flagging this as an upstream issue, sorry, and I will push some code to prevent installation attempts on ARM and ARM64.

**Comment by 4abhinavjain** [comment]
There still seems to be a workaround for arm64 which I could not make it to work but seems very likely. https://github.com/nextcloud/integration_whiteboard/issues/22
